lhdetect2_web/datasets/urls.py
from django.urls import path

from datasets import views

app_name = 'datasets'

urlpatterns = [
    path('', views.index, name='index'),
    path('public/', views.public_datasets, name='public'),
    path('user/', views.user_datasets, name='user'),
    path('create/', views.create_dataset, name='create_dataset'),
    path('upload/', views.upload_image, name='upload_image'),
    path('<int:id>/', views.dataset_images, name='dataset_images'),
    path('<int:id>/delete/', views.delete_dataset, name='delete_dataset')
]

lhdetect2_web/lhdetect2_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from datasets import views
from users import views as users_views

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', users_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('datasets/', include('datasets.urls', namespace='datasets')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lhdetect2_web/datasets/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField
from enum import Enum
from sorl.thumbnail import ImageField

from users.models import CustomUser


class SharingMode(Enum):
    PRIVATE = 'private'
    PUBLIC = 'public'


class GenerationType(Enum):
    CLEAN_LINE = 'clean line'
    HYBRID = 'hybrid'


class GrowthFacility(Enum):
    FIELD = 'field'
    GREENHOUSE = 'greenhouse'
    PLANT_CHAMBER = 'plant chamber'


class Watering(Enum):
    WATERING = 'watering'
    DROUGHT = 'drought'


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class Image(models.Model):
    title = models.CharField(max_length=255, blank=True)
    file = ImageField(upload_to='images/')
    date_uploaded = models.DateTimeField(auto_now_add=True)
    lhdetect_desc = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.title


class Dataset(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=50)
    sharing = models.CharField(max_length=7,
                               choices=[(member.name, member.value) for member in SharingMode],
                               default=SharingMode.PUBLIC.name)

    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    separator = models.CharField(max_length=5, default='_')
    images = models.ManyToManyField(Image)

    parent1 = models.CharField(max_length=200, null=True, blank=True)
    parent2 = models.CharField(max_length=200, null=True, blank=True)
    gen_type = models.CharField(max_length=10, verbose_name="Generation Type",
                                choices=[(member.name, member.value) for member in GenerationType], blank=True)
    generation = models.PositiveSmallIntegerField(null=True, blank=True)

    place = models.CharField(max_length=13,
                             choices=[(member.name, member.value) for member in GrowthFacility], blank=True)
    watering = models.CharField(max_length=8,
                                choices=[(member.name, member.value) for member in Watering], blank=True)

    repetition = models.PositiveIntegerField(null=True, blank=True)
    # TODO: restrict to month and year only
    vegetation_date = models.DateField(null=True, blank=True)

    custom_fields = JSONField(null=True)

    def __str__(self):
        return self.title

lhdetect2_web/datasets/forms.py
from django import forms
from datasets.models import Dataset, Image


class DatasetForm(forms.ModelForm):
    class Meta:
        model = Dataset
        exclude = ['user', 'images', 'custom_fields']


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('file', )

lhdetect2_web/datasets/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.list import ListView
from django.http import JsonResponse
from django.template.loader import render_to_string
import django_tables2 as tables

from datasets.models import Dataset, SharingMode, Image
from datasets.tables import DatasetTable
from datasets.forms import DatasetForm, ImageForm
from datasets.tasks import process_image
from users.models import CustomUser


USER_LIST = 'user'
PUBLIC_LIST = 'public'


def index(request):
    context = {}
    return render(request, 'datasets/index.html', context)


def create_dataset(request):
    data = dict()

    if request.method == 'POST':
        form = DatasetForm(request.POST)
        if form.is_valid():
            dataset = form.save(commit=False)
            dataset.user = CustomUser.objects.get(id=request.user.id)
            dataset.save()

            form_data = request.POST.copy()
            image_ids = form_data.get("images").split(',')
            if image_ids[0] != '':
                images = Image.objects.filter(id__in=image_ids)
                dataset.images.add(*images)

            data['form_is_valid'] = True

            list_type = request.META.get('HTTP_REFERER').split('/')[-2]

            if list_type == USER_LIST:
                datasets = get_user_datasets(request)
            elif list_type == PUBLIC_LIST:
                datasets = get_public_datasets(request)
            else:
                datasets = []

            context = {
                'datasets': datasets
            }

            data['html_dataset_list'] = render_to_string('datasets/includes/partial_dataset_list.html',
                                                         context)
            data['html_dataset_counter'] = render_to_string('datasets/includes/partial_dataset_counter.html',
                                                            context)

        else:
            data['form_is_valid'] = False
    else:
        form = DatasetForm()

    context = {
        'form': form
    }
    data['html_form'] = render_to_string('datasets/includes/partial_dataset_create.html',
                                         context, request=request)

    return JsonResponse(data)


def get_user_datasets(request):
    return Dataset.objects.filter(user_id=request.user.id)


def get_public_datasets(request):
    return Dataset.objects.filter(sharing=SharingMode.PUBLIC.name)


def delete_dataset(request, id):
    dataset = get_object_or_404(Dataset, id=id)

    data = dict()
    if request.method == 'POST':
        dataset.delete()
        data['form_is_valid'] = True

        list_type = request.META.get('HTTP_REFERER').split('/')[-2]

        if list_type == USER_LIST:
            datasets = get_user_datasets(request)
        elif list_type == PUBLIC_LIST:
            datasets = get_public_datasets(request)
        else:
            datasets = []

        context = {
            'datasets': datasets
        }
        data['html_dataset_list'] = render_to_string('datasets/includes/partial_dataset_list.html', context)
    else:
        context = {
            'dataset': dataset
        }
        data['html_form'] = render_to_string('datasets/includes/partial_dataset_delete.html', context, request=request)
    return JsonResponse(data)


def user_datasets(request):
    datasets = get_user_datasets(request)

    context = {
        'datasets': datasets,
        'list_name': 'My Datasets'
    }

    return render(request, 'datasets/datasets_list.html', context)


def public_datasets(request):
    datasets = get_public_datasets(request)

    context = {
        'datasets': datasets,
        'list_name': 'Public Datasets'
    }

    return render(request, 'datasets/datasets_list.html', context)


def dataset_images(request, id):
    dataset = get_object_or_404(Dataset, id=id)
    images = dataset.images.order_by('title')

    context = {
        'dataset': dataset,
        'images': images
    }

    return render(request, 'datasets/dataset_images.html', context)


def upload_image(request):
    form = ImageForm(request.POST, request.FILES)
    if form.is_valid():
        image = form.save(commit=False)
        image.title = image.file.name
        image.save()

        process_image.delay(image.pk)

        data = {
            'is_valid': True,
            'name': image.file.name,
            'url': image.file.url,
            'id': image.pk
        }
    else:
        data = {
            'is_valid': False
        }

    return JsonResponse(data)

lhdetect2_web/templates/datasets/includes/partial_dataset_counter.html
<p class="text-muted">{{ datasets|length }} datasets</p>

lhdetect2_web/templates/datasets/includes/partial_dataset_create.html
<form method="post" action="{% url 'datasets:create_dataset' %}" class="js-dataset-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Add a New Dataset</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6">
          {% include 'includes/form.html' %}
        </div>
        <div class="col-md-6 ml-auto">
          <div>
            <button type="button" id="uploadImages" class="upload btn btn-primary">
              Upload photos
            </button>
            <input id="fileUpload" type="file" name="file" multiple
                   style="display: none;"
                   data-url="{% url 'datasets:upload_image' %}"
                   data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
            <table id="uploadingFiles" class="table table-bordered">
              <thead>
                <tr>
                  <th>Images</th>
                </tr>
              </thead>
              <tbody></tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create</button>
  </div>
</form>

lhdetect2_web/templates/datasets/includes/partial_dataset_delete.html
<form method="post" action="{% url 'datasets:delete_dataset' dataset.id %}" class="js-dataset-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Confirm dataset deletion</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>

  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the dataset <strong>{{ dataset.title }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete</button>
  </div>
</form>

lhdetect2_web/templates/datasets/includes/partial_dataset_list.html
{% for dataset in datasets %}
  <tr>
    <td><a href="{% url 'datasets:dataset_images' dataset.id %}">{{ dataset.title }}</a></td>
    <td>{{ dataset.date_updated }}</td>
    <td>{{ dataset.user.email }}</td>
    <td>
      <button type="button"
              class="btn btn-danger btn-sm js-delete-dataset"
              data-url="{% url 'datasets:delete_dataset' dataset.id %}">Delete</button>
    </td>
  </tr>
{% empty %}
  <tr>
    <td colspan="8" class="text-center bg-warning">No datasets yet.</td>
  </tr>
{% endfor %}